### ISSUE TITLE
Mispelling of 'Paths' in files

### ISSUE THREAD

**Issue by jwhenry3** [PhalconEye/cms#111]
Looking in the repository, I noticed that the word 'paths' is mispelled as 'pathes' in the following files:
![screen shot 2015-03-02 at 9 45 00 am](https://cloud.githubusercontent.com/assets/4164199/6444087/e7767754-c0c0-11e4-9799-6d1a0bbcd95c.png)

As a developer, when I see mispelled words it deters me from using external libraries that might be worth the time to learn, so if others feel the same, this may need to be addressed to improve the appearance of legitimacy.

**Comment by lantian** [comment]
Hi, agreed, but most of this files are from ajaxplorer filemanager =)
Other mispells I will correct, thanks!
